import Head from "next/head";
import { Box, Card, Grid, Typography } from "@mui/material";
import Link from "next/link";
import AssignmentIcon from "@mui/icons-material/Assignment";
import SourceIcon from "@mui/icons-material/Source";

export default function Home() {
  const linksList = [
    {
      title: "Applications",
      icon: <AssignmentIcon sx={{ color: "#aaa", fontSize: "42px" }} />,
      link: "/applications",
    },
    {
      title: "Resources",
      icon: <SourceIcon sx={{ color: "#aaa", fontSize: "42px" }} />,
      link: "/resources",
    },
  ];

  return (
    <>
      <Head>
        <title>Cost Data (2021 Student Task)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box my={3}>
        <Typography component="h1" variant="h1" fontSize="34px" mb={2}>
          Welcome
        </Typography>
        <Grid container spacing={3}>
          {linksList?.map((data: any, index: number) => (
            <Grid key={index} item xs={12} md={6}>
              <Link
                href={data?.link}
                style={{
                  textDecoration: "none",
                }}
              >
                <Card
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    height: "300px",
                  }}
                >
                  <Box textAlign="center">
                    {data?.icon}
                    <Typography>Go to {data?.title}</Typography>
                  </Box>
                </Card>
              </Link>
            </Grid>
          ))}
        </Grid>
      </Box>
    </>
  );
}
